# -*- coding: utf-8 -*-
{'name': 'Contratos e Aditivos Imobiliários Empresarial',
 'summary': 'Gestão empresarial de contratos, aditivos, seleção controlada, parcelas afetadas, recálculo financeiro, documentos e auditoria '
            'para Imóveis',
 'version': '19.0.1.5.0',
 'category': 'Imóveis/Contratos',
 'author': 'Franco Poleo / Manuela Silva',
 'description': ' ',
 'license': 'LGPL-3',
 'depends': ['base', 'mail', 'account', 'analytic', 'property_core'],
 'data': ['security/security.xml',
          'security/ir.model.access.csv',
          'data/sequence.xml',
          'data/amendment_reason_data.xml',
          'views/amendment_views.xml',
        'views/amendment_agenda_views.xml',
          'views/rent_schedule_views.xml',
          'views/billing_views.xml',
          'views/billing_impact_views.xml',
          'views/financial_adjustment_views.xml',
          'views/document_views.xml',
          'views/approval_views.xml',
          'views/obligation_views.xml',
          'views/option_views.xml',
          'views/config_views.xml',
          'views/menu.xml'],
 'installable': True,
 'application': True,
 'auto_install': False}
