{
    "name": "Property Condominium Enterprise",
    "version": "19.0.1.0.0",
    "category": "Real Estate/Condominium",
    "summary": "Enterprise condominium and mall operations for complexes and units",
    "author": "Franco Poleo / Manuela Silva",
    "license": "LGPL-3",
    "depends": [
        "property_core",
        "account",
        "mail",
        "portal",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/property_complex_views.xml",
        "views/property_asset_views.xml",
        "views/res_config_settings_views.xml",
        "views/cnab_profile_views.xml",
        "views/condominium_relationship_views.xml",
        "views/condominium_charge_views.xml",
        "views/condominium_ticket_views.xml",
        "views/condominium_expense_views.xml",
        "wizard/condominium_return_wizard_views.xml",
        "wizard/condominium_report_wizard_views.xml",
        "wizard/condominium_report_line_views.xml",
        "views/condominium_menu_views.xml",
        "views/portal_templates.xml",
    ],
    "demo": [
        "demo/demo.xml",
    ],
    "installable": True,
    "auto_install": False,
}
