from . import property_accounting
from . import property_complex
from . import property_asset
from . import property_asset_communication
from . import property_contract
from . import property_rent
from . import property_inspection
from . import property_maintenance
from . import property_maintenance_bill
from . import property_maintenance_bill_wizard
from . import account_move_ext
from . import property_owner_statement
from . import property_owner_repasse
from . import property_broker_assignment
from . import property_acquisition
from . import property_lead
from . import property_index
from . import property_rent_adjustment
from . import property_agenda_ext
from . import property_commission
from . import property_dashboard
from . import property_media
from . import property_stakeholder_type
from . import property_stakeholder_profile
from . import property_partner_ext
from . import res_partner_property_ext

from . import property_migration_helper

from . import property_rent_enterprise
from . import ir_actions_report_patch
