{
    "name": "Property Core",
    "version": "19.0.6.2.1",
    "category": "Real Estate/Properties",
    "summary": "Gestão de imóveis, contratos, aluguéis, proprietários e comissionamento",
    "author": "Franco Poleo / Manuela Silva",
    "license": "LGPL-3",
    "depends": ["mail", "common_base", "account"],
    "data": [
        "data/property_contact_categories.xml",
        "security/property_security.xml",
        "security/ir.model.access.csv",
        "report/property_contract_report.xml",
        "report/owner_statement_report.xml",
        "report/portfolio_report.xml",
        "report/delinquency_report.xml",
        "report/profitability_report.xml",
        "report/owner_repasse_report.xml",
        "report/property_rent_receipt_report.xml",
        "data/property_activity_types.xml",
        "data/property_index_data.xml",
        "data/property_cron.xml",
        "data/property_binary_tracking_cleanup.xml",
        "data/property_rent_receipt_sequence.xml",
        "data/property_rent_payment_sequence.xml",
        "data/email_templates.xml",
        "data/property_asset_silva.xml",
        "data/property_taxonomy_data.xml",
        "data/property_media_category_data.xml",
        "views/property_stakeholder_type_views.xml",
        "views/property_stakeholder_profile_views.xml",
        "views/property_partner_ext_views.xml",
        "views/res_partner_property_views.xml",
        "views/property_accounting_settings_views.xml",
        "views/property_complex_views.xml",
        "views/property_asset_views.xml",
        "views/property_asset_communication_views.xml",
        "views/property_contract_views.xml",
        "views/property_contract_enterprise_views.xml",
        "views/property_rent_views.xml",
        "views/property_rent_enterprise_views.xml",
        "views/property_media_category_views.xml",
        "views/property_media_views.xml",
        "views/property_inspection_views.xml",
        "views/property_maintenance_views.xml",
        "views/property_maintenance_bill_views.xml",
        "views/property_maintenance_bill_wizard_views.xml",
        "views/account_move_ext_views.xml",
        "views/property_rent_adjustment_views.xml",
        "views/property_agenda_views.xml",
        "wizard/property_media_bulk_wizard_views.xml",
        "views/property_acquisition_views.xml",
        "views/property_index_views.xml",
        "views/property_lead_views.xml",
        "views/property_broker_assignment_views.xml",
        "views/property_commission_views.xml",
        "views/property_owner_repasse_views.xml",
        "views/property_dashboard_views.xml",
        "views/property_menu_views.xml",
        "views/property_settings_config_views.xml",
        "views/property_agenda_menu_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "property_core/static/src/scss/property_asset_kanban.scss",
            "property_core/static/src/scss/property_complex_kanban.scss",
        ]
    },
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
